Repository SOPT-all/35-SOPKATHON-iOS-Team3, pull requests merged in 2024-11, with the labels that each got.

#2 [Setting] #1 - 프로젝트 초기 세팅
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS.xcodeproj/project.pbxproj
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Application/AppDelegate.swift
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Application/SceneDelegate.swift
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Extensions/NSObject+.swift
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Extensions/UILabel+.swift
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Extensions/UIStackView+.swift
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Extensions/UITextField+.swift
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Extensions/UIView+.swift
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Base.lproj/LaunchScreen.storyboard
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Supporting Files/Info.plist
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Presentation/ViewController.swift
Labels: 혜린 🍥, Setting ⚙️

#4 [Setting] #3 - 네트워크 기초 세팅
  .gitignore
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS.xcodeproj/project.pbxproj
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Supporting Files/Info.plist
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Network/Base/BaseService.swift
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Network/Base/BaseTargetType.swift
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Network/Base/MoyaPlugin.swift
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Network/Base/NetworkResult.swift
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Network/Base/NetworkService.swift
Labels: 혜린 🍥, Setting ⚙️, Network 📡

#6 [Setting] #5 - 폰트 스타일 가이드 세팅
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS.xcodeproj/project.pbxproj
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Literals/FontLiterals.swift
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Fonts/Pretendard-Black.otf
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Fonts/Pretendard-Bold.otf
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Fonts/Pretendard-ExtraBold.otf
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Fonts/Pretendard-ExtraLight.otf
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Fonts/Pretendard-Light.otf
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Fonts/Pretendard-Medium.otf
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Fonts/Pretendard-Regular.otf
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Fonts/Pretendard-SemiBold.otf
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Fonts/Pretendard-Thin.otf
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Supporting Files/Info.plist
Labels: 혜린 🍥, Setting ⚙️

#9 [Setting] #8 - 컬러 에셋, 폴더링 추가
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS.xcodeproj/project.pbxproj
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/gray_0.colorset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/gray_10.colorset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/gray_100.colorset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/gray_20.colorset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/gray_30.colorset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/gray_40.colorset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/gray_50.colorset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/gray_60.colorset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/gray_70.colorset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/gray_80.colorset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/gray_90.colorset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/gray_95.colorset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/gray_98.colorset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/primary_200.colorset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/primary_500.colorset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Presentation/Main/MainViewController.swift
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Presentation/Onboarding/OnboardingViewController.swift
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Presentation/Quiz/QuizViewController.swift
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Presentation/Result/ResultViewController.swift
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Presentation/Splash/SplashViewController.swift
Labels: 혜린 🍥, Setting ⚙️

#14 [Fix] #13 - 스타일 가이드 변경사항 적용
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Extensions/UILabel+.swift
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Literals/FontLiterals.swift
Labels: 혜린 🍥, Fix 🔨

#17 [Chore] #16 - GrayScale 변경사항 적용
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/gray_10.colorset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/gray_100.colorset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/gray_20.colorset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/gray_30.colorset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/gray_40.colorset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/gray_50.colorset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/gray_60.colorset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/gray_70.colorset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/gray_80.colorset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/gray_90.colorset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/gray_95.colorset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/gray_98.colorset/Contents.json
Labels: 여경 🐵, Chore 🪡

#21 [Feat] #18 - 퀴즈 결과 뷰 작업
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS.xcodeproj/project.pbxproj
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS.xcodeproj/xcshareddata/xcschemes/35th-SOPKATHON-Team3-iOS.xcscheme
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/gray_10.colorset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/gray_100.colorset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/gray_20.colorset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/gray_30.colorset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/gray_40.colorset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/gray_50.colorset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/gray_60.colorset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/gray_70.colorset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/gray_80.colorset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/gray_90.colorset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/gray_95.colorset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/gray_98.colorset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Presentation/Result/FailView.swift
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Presentation/Result/ResultViewController.swift
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Presentation/Result/SuccessView.swift
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Presentation/Result/ViewController/ExcuseImageViewController.swift
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Presentation/Result/ViewController/ExcuseViewController.swift
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Presentation/Result/ViewController/FailViewController.swift
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Presentation/Result/ViewController/SuccessViewController.swift
Labels: Fix 🔨

#22 [Feat] #7 - 메인뷰
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS.xcodeproj/project.pbxproj
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS.xcodeproj/xcshareddata/xcschemes/35th-SOPKATHON-Team3-iOS.xcscheme
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/bottles/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/bottles/bottle-full.imageset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/bottles/bottle-full.imageset/bottle-full.svg
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/bottles/bottle-half.imageset/Contents.json
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Global/Resources/Assets.xcassets/bottles/bottle-half.imageset/bottle-half.svg
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Presentation/Main/MainViewController.swift
  35th-SOPKATHON-Team3-iOS/35th-SOPKATHON-Team3-iOS/Presentation/Main/WarningViewController.swift
Labels: 유림 🥑, Feat 💻, Add ✚
